# @package _global_

eval_timestamp: ${now:%Y%m%d_%H%M%S}
eval_name: TEST
eval_log_dir: logs_eval/${eval_name}/${eval_timestamp}
checkpoint: null
headless: True
num_envs: 1
export:
  policy: true
  onnx: true
hydra:
  run:
    dir: ${eval_log_dir}
